export { default as Profile } from './profile/Profile';
export { default as Login } from './emptyAccount/components/login/Login';
export { default as Register } from './emptyAccount/components/register/Register';
export { default as Orders } from './orders/Orders';
export { default as OrderDetail } from './orderDetail/OrderDetail';
export { default as Address } from './address/Address';
export { default as Payments } from './payments/Payments';
export { default as EmptyAccount } from './emptyAccount/EmptyAccount';
export { default as Invoicing } from './invoicing/Invoicing';
